site_name: Dusty
theme: readthedocs
repo_url: https://github.com/gamechanger/dusty
repo_name: GitHub
site_author: GameChanger
pages:
  - Home: index.md
  - Installation: installation.md
  - Getting Started:
      - Example Specs: getting-started/index.md
      - Hello World: getting-started/hello-world.md
  - Usage: usage.md
  - Architecture: architecture.md
  - Changelog: changelog.md
  - Contributing: contributing.md
