site_name: Dusty
theme: readthedocs
repo_url: https://github.com/gamechanger/dusty
repo_name: GitHub
site_author: GameChanger
pages:
  - Home: index.md
  - Installation:
    - Installation: installation.md
    - Setup: setup.md
  - Getting Started:
      - Example Specs: getting-started/index.md
      - Hello World!: getting-started/hello-world.md
      - Developing an App: getting-started/developing.md
      - Moving Files Around: getting-started/files.md
  - Usage: usage.md
  - Architecture: architecture.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Contributing: contributing.md
