site_name: Dusty
theme: readthedocs
repo_url: https://github.com/gamechanger/dusty
repo_name: GitHub
site_author: GameChanger
pages:
  - Home: index.md
  - Why Dusty?: why-dusty.md
  - Installation:
    - Installation: installation.md
    - Setup: setup.md
  - Getting Started:
      - Example Specs: getting-started/index.md
      - Hello World!: getting-started/hello-world.md
      - Developing an App: getting-started/developing.md
      - Moving Files Around: getting-started/files.md
  - Dusty Specs:
    - Specs Overview: specs/index.md
    - Bundle Specs: specs/bundle-specs.md
    - App Specs: specs/app-specs.md
    - Lib Specs: specs/lib-specs.md
    - Service Specs: specs/service-specs.md
    - Test Specs: specs/test-specs.md
  - Usage: usage.md
  - Architecture: architecture.md
  - FAQ: faq.md
  - Changelog: changelog.md
  - Contributing: contributing.md
